version: '3.3'

services:
    app:
      image: fbrettnich/hcloud-snapshot-as-backup
      restart: unless-stopped
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        - API_TOKEN=
        - SNAPSHOT_NAME="%name%-%timestamp%"
        - KEEP_LAST=3
        - CRON=0 1 * * *
